terminal: emit unicode output correctly
not ready for upstreaming; this breaks unicode frm starlark; i.e.:
```
fail("├──nfs")
```

produces:
```
ERROR: Traceback (most recent call last):
        File "WORKSPACE.bazel", line 7, column 5, in <toplevel>
                fail("├──nfs")
Error in fail: ââânfs
```

which is a regression...